excerpt_separator: ""
pygments: true
pygments-style: manni
markdown: kramdown
url: http://restoresrl.github.io
title: Restore
tagline: A log of everyday life
description: My awesome new site
paginate: 5
